name: Github Action Build PKGBUILD
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build linux-ck-uksm
        runs:
          using: 'docker'
          image: 'Dockerfile'
          args:
            - ${{ auto_pkgbuild }}
      - uses: ncipollo/release-action@v1.6.1
        with:
          allowUpdates: true
          tag: "5.12.5"
          artifacts: "./*/*.zst"
          token: ${{ secrets.auto_pkgbuild }}
