name: Github Action Build PKGBUILD
on: push
jobs:
  build_for_arch:
    runs-on: ubuntu-latest
    steps:
      - name: Build linux-ck-uksm for arch
        uses: antman666/build-aur-action@mine
        with:
          repo-name: linux-ck-uksm
      - uses: ncipollo/release-action@v1.8.6
        with:
          allowUpdates: true
          tag: "linux-5.12.17-ck-uksm-1_for_arch"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
  build_for_debian:
    runs-on: ubuntu-latest
    steps:
      - name: Build linux-ck-uksm for debian
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install git fakeroot build-essential ncurses-dev libssl-dev bc kernel-package libelf-dev -y
          git clone https://github.com/antman666/linux-ck-uksm
          cd linux-ck-uksm
          bash make_kernel.sh
      - uses: ncipollo/release-action@v1.8.6
        with:
          allowUpdates: true
          tag: "linux-5.12.17-ck-uksm-1_for_debian"
          artifacts: "./*/*.deb"
          token: ${{ secrets.GITHUB_TOKEN }}
