name: Github Action Build PKGBUILD
on: push
jobs:
  build_for_arch:
    runs-on: ubuntu-latest
    steps:
      - name: Build linux-ck-uksm for arch
        uses: antman666/build-aur-action@master
        with:
          repo-name: auto_pkgbuild
      - uses: ncipollo/release-action@v1.6.1
        with:
          allowUpdates: true
          tag: "linux-5.12.8-ck1-uksm for arch"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
  build_for_debian:
    runs-on: ubuntu-latest
    steps:
      - name: Build linux-ck-uksm for debian
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install git fakeroot build-essential ncurses-dev libssl-dev bc kernel-package libelf-dev -y
          git clone https://github.com/antman666/auto_pkgbuild
          cd auto_pkgbuild
          wget -c https://www.kernel.org/pub/linux/kernel/v5.x/linux-5.12.8.tar.xz
          wget -c https://github.com/graysky2/kernel_gcc_patch/archive/20210412.tar.gz
          wget -c http://ck.kolivas.org/patches/5.0/5.12/5.12-ck1/patch-5.12-ck1.xz
          tar -xpvf linux-5.12.8.tar.xz
          tar -xpvf 20210412.tar.gz
          xz -d patch-5.12-ck1.xz

          cd linux-5.12.8
          scripts/setlocalversion --save-scmversion
          patch -Np1 < ../0001-ZEN-Add-sysctl-and-CONFIG-to-disallow-unprivileged-C.patch
          patch -Np1 < ../0002-UKSM.patch

          cp ../config .config

          scripts/config --disable CONFIG_DEBUG_INFO
          scripts/config --disable CONFIG_CGROUP_BPF
          scripts/config --disable CONFIG_BPF_LSM
          scripts/config --disable CONFIG_BPF_PRELOAD
          scripts/config --disable CONFIG_BPF_LIRC_MODE2
          scripts/config --disable CONFIG_BPF_KPROBE_OVERRIDE

          scripts/config --enable CONFIG_PSI_DEFAULT_DISABLED

          scripts/config --disable CONFIG_LATENCYTOP
          scripts/config --disable CONFIG_SCHED_DEBUG

          scripts/config --disable CONFIG_KVM_WERROR

          sed -i -re "s/^(.EXTRAVERSION).*$/\1 = /" "../patch-5.12-ck1"

          patch -Np1 -i ../patch-5.12-ck1

          make olddefconfig

          patch -Np1 -i "../kernel_gcc_patch-20210412/more-uarches-for-kernel-5.8+.patch"

          yes "" | make oldconfig
          make -s kernelrelease > version
          
          fakeroot make-kpkg --initrd --revision=5.12.8 kernel_image kernel_headers -j40

      - uses: ncipollo/release-action@v1.6.1
        with:
          allowUpdates: true
          tag: "linux-5.12.8-ck1-uksm for debian"
          artifacts: "./*/*.deb"
          token: ${{ secrets.GITHUB_TOKEN }}
