name: Github Action Build PKGBUILD
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build linux-ck-uksm
        uses: antman666/build-aur-action@master
        with:
          repo-name: auto_pkgbuild
      - uses: ncipollo/release-action@v1.6.1
        with:
          allowUpdates: true
          tag: "linux-5.12.8-ck1-uksm"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
