name: Github Action Build PKGBUILD
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build linux-ck-uksm
        uses: antman666/build-aur-action@master
        with:
          repo-name: linux-ck-uksm
      - uses: ncipollo/release-action@v1.6.1
        with:
          allowUpdates: true
          tag: "5.12.7"
          artifacts: "./*/*.zst"
          token: ${{ secrets.auto_pkgbuild }}
