name: Github Action Build PKGBUILD
on: push
jobs:
  build_for_arch:
    runs-on: ubuntu-latest
    steps:
      - name: Build linux-ck-uksm for arch
        uses: antman666/build-aur-action@master
        with:
          repo-name: linux-ck1-uksm
      - uses: ncipollo/release-action@v1.8.6
        with:
          allowUpdates: true
          tag: "linux-5.12.12-ck-uksm_for_arch"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
  build_for_debian:
    runs-on: ubuntu-latest
    steps:
      - name: Build linux-ck-uksm for debian
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install git fakeroot build-essential ncurses-dev libssl-dev bc kernel-package libelf-dev -y
          git clone https://github.com/antman666/auto_pkgbuild
          cd auto_pkgbuild
          wget -c https://www.kernel.org/pub/linux/kernel/v5.x/linux-5.12.12.tar.xz
          wget -c https://github.com/graysky2/kernel_compiler_patch/archive/20210610.tar.gz
          wget -c http://ck.kolivas.org/patches/5.0/5.12/5.12-ck1/patch-5.12-ck1.xz
          tar -xpvf linux-5.12.12.tar.xz
          tar -xpvf 20210610.tar.gz
          xz -d patch-5.12-ck1.xz

          cd linux-5.12.12
          scripts/setlocalversion --save-scmversion
          local src
          for src in "${source[@]}"; do
                src="${src%%::*}"
                src="${src##*/}"
                [[ $src = 0*.patch ]] || continue
                echo "Applying patch $src..."
                patch -Np1 < "../$src"
          done


          cp ../config.debian .config

          scripts/config --disable CONFIG_DEBUG_INFO
          scripts/config --disable CONFIG_CGROUP_BPF
          scripts/config --disable CONFIG_BPF_LSM
          scripts/config --disable CONFIG_BPF_PRELOAD
          scripts/config --disable CONFIG_BPF_LIRC_MODE2
          scripts/config --disable CONFIG_BPF_KPROBE_OVERRIDE

          scripts/config --enable CONFIG_PSI_DEFAULT_DISABLED

          scripts/config --disable CONFIG_LATENCYTOP
          scripts/config --disable CONFIG_SCHED_DEBUG

          scripts/config --disable CONFIG_KVM_WERROR

          sed -i -re "s/^(.EXTRAVERSION).*$/\1 = /" "../patch-5.12-ck1"

          patch -Np1 -i ../patch-5.12-ck1

          make olddefconfig

          patch -Np1 -i "../kernel_compiler_patch-20210610/more-uarches-for-kernel-5.8+.patch"

          yes "" | make oldconfig
          make -s kernelrelease > version
          
          fakeroot make-kpkg --initrd --revision=5.12.12 --append-to-version="-ck-uksm" kernel_image kernel_headers -j40

      - uses: ncipollo/release-action@v1.8.6
        with:
          allowUpdates: true
          tag: "linux-5.12.12-ck-uksm_for_debian"
          artifacts: "./*/*.deb"
          token: ${{ secrets.GITHUB_TOKEN }}
